---
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    labels:
      - "dependencies"
      - "go"
      - "type::chore"
    schedule:
      interval: "weekly"
    groups:
      security:
        update-types:
          - "patch"
          - "minor"
      k8s.io:
        patterns:
          - "k8s.io/*"
      rook:
        patterns:
          - "github.com/rook/rook*"

  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "dependencies"
      - "github-actions"
      - "type::chore"
    schedule:
      interval: "weekly"
