name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:

  release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - run: make docker-image DOCKER_IMAGE=replicated/ekco:$GITHUB_REF_NAME VERSION=$GITHUB_REF_NAME
      - run: docker push replicated/ekco:$GITHUB_REF_NAME
