name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:

  publish-securebuild:
    if: ${{ !contains(github.ref_name, '-') && !contains(github.ref_name, '+') }}
    uses: ./.github/workflows/publish-securebuild.yml
    with:
      version: ${{ github.ref_name }}
    secrets:
      SECUREBUILD_API_TOKEN: ${{ secrets.SECUREBUILD_API_TOKEN }}
