name: scheduled-scan
on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch: {}

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Run Grype filesystem vulnerability scanner
        id: scan
        uses: ./.github/actions/scan-filesystem
        with:
          path: '.'
          fail-build: 'true'
          severity-cutoff: 'medium'
          output-file: 'grype-filesystem-results.sarif'
          only-fixed: 'true'
          retention-days: '90'
          category-prefix: 'filesystem-scan-'
